import 'package:hive_flutter/hive_flutter.dart';
import 'package:habit_iq/features/habit/data/models/habit_model.dart';
import 'package:habit_iq/features/mood/data/models/mood_entry_model.dart';
import 'package:habit_iq/features/profile/data/models/user_model.dart';

/// ─────────────────────────────────────────────────────────────────────────────
/// Box name constants — single source of truth to avoid typos.
/// ─────────────────────────────────────────────────────────────────────────────
class HiveBoxes {
  HiveBoxes._();
  static const String user = 'userBox';
  static const String habits = 'habitsBox';
  static const String moods = 'moodsBox';
  static const String settings = 'settingsBox';
}

/// ─────────────────────────────────────────────────────────────────────────────
/// Singleton service that manages all Hive initialization and box access.
///
/// Usage:
/// ```dart
/// await HiveService.init();           // call once in main()
/// final box = HiveService.habitsBox;  // then access boxes anywhere
/// ```
/// ─────────────────────────────────────────────────────────────────────────────
class HiveService {
  HiveService._(); // private constructor — no instances

  // ── Typed box accessors ────────────────────────────────────────────────────

  /// Box storing a single [UserModel] keyed by user-id.
  static late Box<UserModel> userBox;

  /// Box storing all [HabitModel] entries, keyed by habit id.
  static late Box<HabitModel> habitsBox;

  /// Box storing all [MoodEntryModel] entries, keyed by entry id.
  static late Box<MoodEntryModel> moodsBox;

  /// Generic settings box — stores primitive key-value pairs
  /// (e.g. theme preference, onboarding completion flag).
  static late Box<dynamic> settingsBox;

  // ── Initialisation ─────────────────────────────────────────────────────────

  /// Must be awaited **before** [runApp] in `main()`.
  ///
  /// Steps:
  ///  1. Initialises Hive with the Flutter path provider.
  ///  2. Registers all generated TypeAdapters (idempotent — safe to call twice).
  ///  3. Opens every box the app needs.
  static Future<void> init() async {
    // 1. Init Hive storage location.
    await Hive.initFlutter();

    // 2. Register TypeAdapters (generated by build_runner).
    _registerAdapters();

    // 3. Open boxes — all parallel for faster startup.
    await Future.wait([
      Hive.openBox<UserModel>(HiveBoxes.user).then((b) => userBox = b),
      Hive.openBox<HabitModel>(HiveBoxes.habits).then((b) => habitsBox = b),
      Hive.openBox<MoodEntryModel>(HiveBoxes.moods).then((b) => moodsBox = b),
      Hive.openBox<dynamic>(HiveBoxes.settings).then((b) => settingsBox = b),
    ]);
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  /// Registers all Hive adapters if not already registered.
  /// Guard with [Hive.isAdapterRegistered] prevents duplicate-registration errors.
  static void _registerAdapters() {
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(UserModelAdapter());
    }
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(HabitModelAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(MoodEntryModelAdapter());
    }
  }

  /// Clears all user-specific data from Hive.
  ///
  /// Call this before starting a new user session (guest or otherwise) so the
  /// new user starts with a completely clean slate.
  static Future<void> clearAllUserData() async {
    await Future.wait([habitsBox.clear(), moodsBox.clear(), userBox.clear()]);
  }

  /// Safely closes all open boxes — call on app disposal if needed.
  static Future<void> close() async {
    await Hive.close();
  }
}
