// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBituB1SnIGcJuReLuz4Km-ugdih-OhZHY',
    appId: '1:933760355804:web:8006bfa2117fac6cc21319',
    messagingSenderId: '933760355804',
    projectId: 'habitiq-fc18b',
    authDomain: 'habitiq-fc18b.firebaseapp.com',
    storageBucket: 'habitiq-fc18b.firebasestorage.app',
    measurementId: 'G-ZBL8W2LCDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFXp9Bze22579bUpexRe_ogeZwpuUMW-4',
    appId: '1:933760355804:android:918f70f3f075a101c21319',
    messagingSenderId: '933760355804',
    projectId: 'habitiq-fc18b',
    storageBucket: 'habitiq-fc18b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wEswJRAlF4i9Nvn0GvBs_KRMHh11xSk',
    appId: '1:933760355804:ios:8ad90ff7b67a76ccc21319',
    messagingSenderId: '933760355804',
    projectId: 'habitiq-fc18b',
    storageBucket: 'habitiq-fc18b.firebasestorage.app',
    iosClientId: '933760355804-op19vij7qfs17achidrbfc3sflner91k.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wEswJRAlF4i9Nvn0GvBs_KRMHh11xSk',
    appId: '1:933760355804:ios:8ad90ff7b67a76ccc21319',
    messagingSenderId: '933760355804',
    projectId: 'habitiq-fc18b',
    storageBucket: 'habitiq-fc18b.firebasestorage.app',
    iosClientId: '933760355804-op19vij7qfs17achidrbfc3sflner91k.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBituB1SnIGcJuReLuz4Km-ugdih-OhZHY',
    appId: '1:933760355804:web:ae3e0193d139c667c21319',
    messagingSenderId: '933760355804',
    projectId: 'habitiq-fc18b',
    authDomain: 'habitiq-fc18b.firebaseapp.com',
    storageBucket: 'habitiq-fc18b.firebasestorage.app',
    measurementId: 'G-W3MXZEYSWL',
  );
}
